### ISSUE TITLE
does not work with angularjs

### ISSUE THREAD

**Issue by krvikash35** [tagawa/bootstrap-without-jquery#46]
it is good idea to not use big fat jquery for small bootstrap event for performance issue...I thought to use  this small code to acheive this..but it does not work in angular..I guess ...will use ui-bootstrap for that.

**Comment by thednp** [comment]
I had a user saying same thing for my bootstrap.native project. I believe you forgot to link the bootstrap-without-jquery.js in the footer.

**Comment by krvikash35** [comment]
@thednp ..it work..but in some situation id does not work..e.g when dropdown is direclty in page, and page is loaded then it work..but if dropdown is being loaded from different partial using ng-include then it does not work...i guess it is because, code is trying to set event listener for dropdown but include-document has not yet loaded the dropdown..with some hack(using event listner $includeContentLoaded), it worked...Anyway its really nice little addition that i will use for some other project.

**Comment by thednp** [comment]
for any additional after `domContentLoaded()` you need to initiate the dropdown, and any other script. I mean [these lines](https://github.com/tagawa/bootstrap-without-jquery/blob/master/bootstrap3/bootstrap-without-jquery.js#L236-L242)

**Comment by krvikash35** [comment]
ok. This way works.
