### ISSUE TITLE
Dynamic dropdowns don't work

### ISSUE THREAD

**Issue by ArtskydJ** [tagawa/bootstrap-without-jquery#49]
I am using a frontend view library that adds the navbar. If the script loads before the navbar elements are in place, the dropdowns don't work. If I load the script after the navbar elements are in place, the dropdowns work, if they're not modified dynamically by the frontend view library.

I'd like to have the dropdowns to be able to be modified by the frontend view library, and still work with this library.

With jquery + bootstrap this is possible.

Thanks for all your work in this cool project, btw!

**Comment by thednp** [comment]
Hey, give [this script](https://github.com/thednp/bootstrap.native/blob/master/lib/dropdown-native.js) a try.
